services:
  backend:
    container_name: demo-backend
    build: ./backend
    networks:
      - frontend_net
      - backend_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo-db:5432/demo-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=supersafe
  frontend:
    container_name: demo-frontend
    build: ./frontend
    networks:
      frontend_net:
    ports:
      - 443:443
    depends_on:
      - backend
    volumes:
      - ./frontend/ssl/:/etc/nginx/certs/
  db:
    image: 'postgres:13-alpine'
    container_name: demo-db
    networks:
        - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=demo-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersafe
networks:
  frontend_net:
  backend_net: