services:
  backend:
    container_name: demo-backend
    build: ./backend
    networks:
      - frontend_net
      - backend_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo-db:5432/demo-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=supersafe
    depends_on:
      - db
  frontend:
    container_name: demo-frontend
    build: ./frontend
    networks:
      frontend_net:
    ports:
      - 4200:80
    depends_on:
      - backend
  db:
    image: 'postgres:13-alpine'
    container_name: demo-db
    networks:
        - backend_net
    environment:
      - POSTGRES_DB=demo-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersafe
networks:
  frontend_net:
  backend_net: