version: '3'
services:
  backend:
    container_name: demo-backend
    build: ./backend
    # remove comments below to make demo-backend callable from host...
    #ports:
    #  - 8080:8080
    networks:
      - frontend_net
      - backend_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo-db:5432/demo-database
      - SPRING_DATASOURCE_USERNAME=demo-admin
      - SPRING_DATASOURCE_PASSWORD=supersafe
  frontend:
    container_name: demo-frontend
    build: ./frontend
    networks:
      frontend_net:
    ports:
      - 4200:80
  db:
    image: 'postgres:13-alpine'
    container_name: demo-db
    networks:
        - backend_net
    environment:
      - POSTGRES_DB=demo-database
      - POSTGRES_USER=demo-admin
      - POSTGRES_PASSWORD=supersafe
networks:
  frontend_net:
  backend_net: